# Generated by Django 5.2.8 on 2025-11-08 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookSolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("book_url", models.URLField(verbose_name="링크")),
                (
                    "cover_url",
                    models.URLField(blank=True, null=True, verbose_name="사진 링크"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HappyTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="VideoSolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("video_url", models.URLField(verbose_name="영상 링크")),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, null=True, verbose_name="썸네일 링크"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                (
                    "happy_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="happyTest.happytest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("score", models.IntegerField(default=0)),
                ("type", models.CharField(max_length=1, verbose_name="타입")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="happyTest.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a_type_score", models.IntegerField(default=0)),
                ("b_type_score", models.IntegerField(default=0)),
                ("c_type_score", models.IntegerField(default=0)),
                ("d_type_score", models.IntegerField(default=0)),
                ("e_type_score", models.IntegerField(default=0)),
                ("f_type_score", models.IntegerField(default=0)),
                ("final_a_type_score", models.FloatField(default=0)),
                ("final_b_type_score", models.FloatField(default=0)),
                ("final_c_type_score", models.FloatField(default=0)),
                ("final_d_type_score", models.FloatField(default=0)),
                ("final_e_type_score", models.FloatField(default=0)),
                ("final_f_type_score", models.FloatField(default=0)),
                ("total_score", models.IntegerField(default=0)),
                ("final_total_score", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "happyTest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="happyTest.happytest",
                    ),
                ),
            ],
        ),
    ]
