# Generated by Django 5.2.8 on 2025-11-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("happyTest", "0002_booksolution_age_result_age_videosolution_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="booksolution",
            name="keyword",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="키워드"
            ),
        ),
        migrations.AddField(
            model_name="videosolution",
            name="keyword",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="키워드"
            ),
        ),
    ]
